# Generated by Django 5.1.4 on 2024-12-13 04:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100.0)], verbose_name='Monto Solicitado')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Aprobado')),
                ('tipo_prestamo', models.CharField(choices=[('personal', 'Préstamo Personal'), ('hipotecario', 'Préstamo Hipotecario'), ('vehicular', 'Préstamo Vehicular'), ('empresarial', 'Préstamo Empresarial')], max_length=20, verbose_name='Tipo de Préstamo')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='solicitado', max_length=15, verbose_name='Estado del Préstamo')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('plazo_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo en Meses')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_primer_pago', models.DateField(blank=True, null=True, verbose_name='Fecha del Primer Pago')),
                ('cuenta_asociada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_asociados', to='cuentas.cuenta', verbose_name='Cuenta Asociada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
