# Generated by Django 5.1.4 on 2024-12-13 04:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True, verbose_name='Número de Tarjeta')),
                ('tipo_tarjeta', models.CharField(choices=[('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Débito')], max_length=10, verbose_name='Tipo de Tarjeta')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=15, verbose_name='Estado de la Tarjeta')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('cvv', models.CharField(max_length=4, verbose_name='Código de Seguridad')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Límite de Crédito')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Saldo Disponible')),
                ('cuenta_asociada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas_asociadas', to='cuentas.cuenta', verbose_name='Cuenta Asociada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
